name: Generate Env File

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create environment file based on branch
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env.production
          else
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" >> .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          fi

      - name: Upload env file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: |
            .env.local
            .env.production
