name: Upload Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: hello.txt
