name: Generate Env File

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  generate-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create environment file based on branch
        run: |
          echo "Branch: ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" > .env.production
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" > .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          else
            echo "Unsupported branch"
            exit 1
          fi

      - name: Debug - list files before upload
        run: ls -alh

      - name: Upload .env.production artifact
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env.production

      - name: Upload .env.local artifact
        if: ${{ github.ref_name == 'dev' }}
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env.local
