name: Generate Env File

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate env for'
        required: true
        default: 'main'

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Create env file based on branch
        run: |
          BRANCH=${{ github.ref_name }} 
          echo "Branch is $BRANCH"
          if [ "$BRANCH" = "main" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" > .env.production
          elif [ "$BRANCH" = "dev" ]; then
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" > .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

      - name: List files for debug
        run: ls -la

      - name: Upload env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file-${{ github.ref_name }}
          path: ${{ github.ref_name == 'main' && '.env.production' || '.env.local' }}
