name: Generate and Use Env File

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate env for'
        required: false
        default: ''

jobs:
  generate-env:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v3

      - name: Set BRANCH variable
        id: set-branch
        run: |
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Debug branch
        run: |
         echo "Detected branch: ${{ steps.set-branch.outputs.branch }}"

      - name: Create env file
        run: |
          if [ "${{ steps.set-branch.outputs.branch }}" = "main" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" > .env.production
          elif [ "${{ steps.set-branch.outputs.branch }}" = "dev" ]; then
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" > .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          else
            echo "Unsupported branch: ${{ steps.set-branch.outputs.branch }}"
            exit 1
          fi

      - name: Set artifact path
        id: set-path
        run: |
          if [ "${{ steps.set-branch.outputs.branch }}" = "main" ]; then
            echo "path=.env.production" >> $GITHUB_OUTPUT
          else
            echo "path=.env.local" >> $GITHUB_OUTPUT
          fi

      - name: Upload env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file-${{ steps.set-branch.outputs.branch }}
          path: ${{ steps.set-path.outputs.path }}

  use-env:
    needs: generate-env
    runs-on: ubuntu-latest
    steps:
      - name: Download env artifact
        uses: actions/download-artifact@v4
        with:
          name: env-file-${{ needs.generate-env.outputs.branch }}
          path: ./envfiles

      - name: List downloaded files
        run: ls -la ./envfiles

      - name: Show env file content
        run: cat ./envfiles/*
