name: Generate Env File

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate env for'
        required: false
        default: ''

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set BRANCH variable
        run: |
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          else
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Debug branch
        run: |
          echo "Detected branch: ${{ env.BRANCH }}"

      - name: Create env file
        run: |
          if [ "${{ env.BRANCH }}" = "main" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" > .env.production
          elif [ "${{ env.BRANCH }}" = "dev" ]; then
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" > .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          else
            echo "Unsupported branch: ${{ env.BRANCH }}"
            exit 1
          fi

      - name: Upload env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file-${{ env.BRANCH }}
          path: ${{ env.BRANCH == 'main' && '.env.production' || '.env.local' }}
