name: Generate Env File

on:
  push:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  generate-env:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create environment file based on branch
        run: |
          echo "Running on branch: ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "Creating .env.production"
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env.production
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "Creating .env.local"
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" >> .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          else
            echo "No matching environment for this branch"
            exit 1
          fi

      - name: Upload .env.local if it exists
        if: ${{ github.ref_name == 'dev' }}
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env.local

      - name: Upload .env.production if it exists
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env.production
