name: Test Upload Artifact

on: [push]

jobs:
  test-upload:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - run: echo "test" > test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt
