name: Generate Env File

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate env for'
        required: false
        default: ''

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set clean branch name into env var
      - name: Set branch variable
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Debug branch info
        run: echo "Branch is $BRANCH"

      - name: Create env file based on branch
        run: |
          if [ "$BRANCH" = "main" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" > .env.production
          elif [ "$BRANCH" = "dev" ]; then
            echo "API_KEY=${{ secrets.DEV_API_KEY }}" > .env.local
            echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> .env.local
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

      - name: List files for debug
        run: ls -la

      - name: Upload env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file-${{ env.BRANCH }}
          path: ${{ env.BRANCH == 'main' && '.env.production' || '.env.local' }}
