name: Generate and Use Env File

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  generate-env:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' || '' }}

    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set BRANCH variable
        id: set-branch
        run: |
          echo "GITHUB EVENT INPUT BRANCH: ${{ github.event.inputs.branch }}"
          echo "GITHUB REF NAME: ${{ github.ref_name }}"
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create env file from current environment
        id: create-env
        run: |
          BRANCH=${{ steps.set-branch.outputs.branch }}
          echo "Using branch: $BRANCH"
          if [[ "$BRANCH" == "main" ]]; then
            ENV_FILE=".env.production"
          elif [[ "$BRANCH" == "dev" ]]; then
            ENV_FILE=".env.local"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi
          echo "Creating $ENV_FILE from environment variables"
          printenv | grep -v '^PWD=' | grep -v '^HOME=' | grep -v '^RUNNER_' > "$ENV_FILE"
          echo "envfile=$ENV_FILE" >> $GITHUB_OUTPUT
          echo "Created:"
          cat "$ENV_FILE"

      - name: Upload env artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: env-file-${{ steps.set-branch.outputs.branch }}
          path: ${{ steps.create-env.outputs.envfile }}

      - name: Set GitHub Environment Secrets from env file
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ENV_FILE=${{ steps.create-env.outputs.envfile }}
          echo "Reading $ENV_FILE and setting secrets in environment: ${{ steps.set-branch.outputs.branch }}"
          if [ ! -f "$ENV_FILE" ]; then
            echo "Error: $ENV_FILE does not exist."
            exit 1
          fi

          while IFS='=' read -r key value; do
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            if [[ -n "$key" && -n "$value" ]]; then
              echo "Setting secret $key"
              gh secret set "$key" --body "$value" --env "${{ steps.set-branch.outputs.branch }}"
            fi
          done < "$ENV_FILE"