name: Generate and Use Env File + Update Amplify

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  generate-env:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' || '' }}

    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}

    steps:
      - uses: actions/checkout@v3

      - name: Set BRANCH variable
        id: set-branch
        run: |
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create env file
        run: |
          if [ "${{ steps.set-branch.outputs.branch }}" = "main" ]; then
            {
              echo "API_KEY=${{ secrets.API_KEY }}"
              echo "API_KEY_1=${{ secrets.API_KEY_1 }}"
              echo "API_KEY_2=${{ secrets.API_KEY_2 }}"
            } > .env.production
          elif [ "${{ steps.set-branch.outputs.branch }}" = "dev" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" > .env.local
          else
            echo "Unsupported branch: ${{ steps.set-branch.outputs.branch }}"
            exit 1
          fi

      - name: Set artifact path
        id: set-path
        run: |
          if [[ "${{ steps.set-branch.outputs.branch }}" = "main" ]]; then
            echo "path=.env.production" >> $GITHUB_OUTPUT
          else
            echo "path=.env.local" >> $GITHUB_OUTPUT
          fi

      - name: Upload env artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: env-file-${{ steps.set-branch.outputs.branch }}
          path: ${{ steps.set-path.outputs.path }}

  update-amplify-env:
    needs: generate-env
    runs-on: ubuntu-latest
    if: ${{ needs.generate-env.outputs.branch != '' }}

    steps:
      - name: Debug Secrets
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}"
          echo "API_KEY_1=${{ secrets.API_KEY_1 }}"
          echo "API_KEY_2=${{ secrets.API_KEY_2 }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AMPLIFY_APP_ID=${{ secrets.AMPLIFY_APP_ID }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Amplify Environment Variables
        run: |
          aws amplify update-backend-environment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --environment-name ${{ needs.generate-env.outputs.branch }} \
            --environment-variables \
            "API_KEY=${{ secrets.API_KEY }},API_KEY_1=${{ secrets.API_KEY_1 }},API_KEY_2=${{ secrets.API_KEY_2 }}"
