name: Sync Local Env to GitHub Environment

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  sync-env:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' || '' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set BRANCH variable
        id: set-branch
        run: |
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Run environment sync script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scripts/sync-env.sh
          ./scripts/sync-env.sh "${{ steps.set-branch.outputs.branch }}"
